%%{init: {
	'logLevel': 'debug',
	'theme': 'base',
	'themeVariables': {
		'commitLabelFontSize': '10px',
		'commitLabelColor': '#111111',
		'commitLabelBackground': '#ffffff',
		'tagLabelFontSize': '10px',
		'tagLabelColor': '#ffffff',
		'tagLabelBackground': '#323765',
		'tagLabelBorder': '#323765',
		'git0': '#ff4930',
		'git1': '#f6c65b',
		'git2': '#02ccd5'
  },
	'gitGraph': {
		'showBranches': true,
		'showCommitLabel': true,
		'mainBranchName': 'staging'
	}
}}%%
gitGraph
	commit id: "…"
	commit id: "af2f5e9" tag: "origin/staging"
	commit id: "ef40b40" type: HIGHLIGHT
	commit id: "8caaadd" type: HIGHLIGHT
	commit id: "dd81f00" type: HIGHLIGHT
	commit id: "f94bbb3" type: HIGHLIGHT
	commit id: "60+ commits..." type: HIGHLIGHT
	commit id: "6854a97" tag: "HEAD" type: HIGHLIGHT
