%%{init: {
	'logLevel': 'debug',
	'theme': 'base',
	'themeVariables': {
		'commitLabelFontSize': '10px',
		'commitLabelColor': '#111111',
		'commitLabelBackground': '#ffffff',
		'tagLabelFontSize': '10px',
		'tagLabelColor': '#ffffff',
		'tagLabelBackground': '#323765',
		'tagLabelBorder': '#323765',
		'git0': '#ff4930',
		'git1': '#f6c65b',
		'git2': '#02ccd5'
  },
	'gitGraph': {
		'showBranches': true,
		'showCommitLabel':true,
		'mainBranchName': 'staging'
	}
}}%%
gitGraph
	commit id: "..."
	commit id: "af2f5e9" tag: "origin/staging"
	branch main
	commit id: "ef40b40"
	commit id: "8caaadd"
	commit id: "dd81f00"
	commit id: "60+ commits..."
	commit id: "6854a97" tag: "origin/main"
	checkout staging
	merge main id: "MERGE commit" tag: "HEAD" type: HIGHLIGHT