%%{init: {
	'logLevel': 'debug',
	'theme': 'base',
	'themeVariables': {
		'commitLabelColor': '#111111',
		'commitLabelBackground': '#ffffff',
		'tagLabelFontSize': '14px',
		'tagLabelColor': '#ffffff',
		'tagLabelBackground': '#ff4930',
		'tagLabelBorder': '#ff4930',
		'gitInv0': '#ff4930'
  },
	'gitGraph': {
		'showBranches': true,
		'showCommitLabel':true
	}
}}%%
gitGraph
	commit id: "0865592"
	commit id: "af2f5e9" tag: "origin/staging" type: HIGHLIGHT
	commit id: "ef40b40"
	commit id: "8caaadd"
	commit id: "dd81f00"
	commit id: "f94bbb3"
	commit id: "60+ commits..."
	commit id: "6854a97" tag: "HEAD" type: HIGHLIGHT
